export const ADICIONAR_ITEM_CARRINHO = 'ADICIONAR_ITEM_CARRINHO';
export const REMOVER_ITEM_CARRINHO = 'REMOVER_ITEM_CARRINHO';
export const LISTAR_ITENS_CARRINHO = 'LISTAR_ITENS_CARRINHO';
export const INCREMENTAR_QTDE = 'INCREMENTAR_QTDE';
export const DECREMENTAR_QTDE = 'DECREMENTAR_QTDE';
